<script setup lang="ts">
const { role, screen, qr, name, ready, taps, seconds, players, started, growth, finished, stage, rank, allRacers, connectionError, busy, joinRoom, startGame, leaveGame, water } = useBloomRoom()
</script>
<template><main class="shell"><nav><a class="brand" href="#"><span>✿</span> BLOOM RUSH</a><div class="live"><i/> ROOM #SPROUT</div></nav>
<p v-if="connectionError" role="alert">{{connectionError}}</p>
<p v-if="screen==='play' && !started" role="status">Get ready! Everyone starts together…</p>
<section v-if="screen==='lobby'" class="lobby"><div class="intro"><div class="eyebrow">HOST CONTROL</div><h1>Scan. Join.<br><em>Grow!</em></h1><p>Ask every gardener to scan the code. They’ll wait safely in the lobby until you start the race.</p><div class="steps"><span><b>1</b> Scan QR</span><span><b>2</b> Wait in lobby</span><span><b>3</b> Host starts</span></div></div><div class="join-card host-card"><div class="card-top"><span>SCAN TO JOIN</span><strong>#SPROUT</strong></div><img v-if="qr" class="real-qr" :src="qr" alt="QR code to join"><div v-else class="qr-loading">Growing QR…</div><h2>Join the watering race</h2><p>Participants scan this code and wait for you.</p><div class="ready-list"><span v-for="p in players" :key="p.id"><i>{{p.name[0]?.toUpperCase()}}</i>{{p.name}} <b>READY</b></span><span v-if="!players.length">Waiting for gardeners…</span></div><button :disabled="!players.length" @click="startGame">START GAME <span>→</span></button><small><i/> {{players.length}} gardener{{players.length===1?'':'s'}} waiting</small></div></section>
<section v-else-if="screen==='waiting'" class="waiting-page"><div class="waiting-card"><div class="seed-pulse">🌱</div><div class="eyebrow">ROOM #SPROUT</div><h1>You’re in!</h1><p>{{ready?"You’re ready to grow. The game will begin when the host presses Start Game.":"Choose your gardener name, then get ready."}}</p><template v-if="!ready"><label>Your nickname<input v-model="name" maxlength="12" @keyup.enter="joinRoom"></label><button @click="joinRoom">I’M READY <span>→</span></button></template><div v-else class="waiting-status"><i/><b>WAITING FOR HOST</b><span>Keep this page open</span></div><div class="waiting-dots"><i/><i/><i/></div></div></section>
<section v-else class="game"><header class="game-head"><div><button class="back" @click="leaveGame">←</button><span>{{role==='host'?'HOST VIEW':'ROOM #SPROUT'}}</span></div><div class="timer"><small>TIME LEFT</small><b>00:{{String(seconds).padStart(2,'0')}}</b></div><div v-if="role==='host'" class="rank"><small>YOUR RANK</small><b>#{{rank}}</b></div></header><div class="race-grid" :class="{solo:role==='player'}"><div class="garden-panel"><div class="water-drops">💧　💧</div><div class="plant-wrap"><div class="sun">☀</div><div class="plant" :class="{'finished-flower':finished}" :style="{transform:`scale(${.7+growth/260})`}">{{stage}}</div><div class="soil"/></div><div class="growth-copy"><span>YOUR PLANT</span><b>FULL BLOOM GOAL</b></div><div class="meter"><i :style="{width:`${growth}%`}"/></div></div><div v-if="role==='host'" class="leaderboard"><div class="eyebrow">LIVE LEADERBOARD</div><h2>Garden race</h2><div v-for="(r,i) in allRacers" :key="r.name" class="racer" :class="{you:r.name===name}"><strong>{{i+1}}</strong><i :style="{background:r.color}">{{r.name[0]?.toUpperCase()}}</i><span>{{r.name}}<small>{{r.score>=85?'Blooming!':r.score>=60?'Growing strong':'Keep tapping'}}</small></span><b>{{r.score}}%</b></div></div></div><div class="tap-zone"><div><span>{{finished?'🏆':seconds<=0?'⏱':'💧'}}</span><h2>{{finished?'You bloomed!':seconds<=0?'Time’s up!':'Water your plant!'}}</h2><p>{{finished?'Your flower reached a glorious full bloom!':seconds<=0?'The garden needs a little more water.':'Keep tapping to grow a full bloom'}}</p></div><button class="water-btn" :disabled="seconds<=0||finished" @pointerdown="water"><span>💧</span>TAP TO WATER<small>{{finished?'FULL BLOOM!':'KEEP WATERING'}}</small></button></div></section><footer><span>GROW TOGETHER. BLOOM FASTER.</span><span>Made for joyful teams 🌱</span></footer></main></template>
