<script setup lang="ts">
import QRCode from "qrcode"
type Screen = "lobby" | "waiting" | "play"
type Participant = { id:string; name:string; score:number; ready:boolean }
const role=ref<"host"|"player">("host"), screen=ref<Screen>("lobby"), qr=ref(""), name=ref("You"), ready=ref(false), taps=ref(0), seconds=ref(25)
const players=ref<Participant[]>([]), gameId=ref(0), participantId=ref(""), started=ref(false)
let timer:ReturnType<typeof setInterval>|null=null, poller:ReturnType<typeof setInterval>|null=null
const growth=computed(()=>Math.round(taps.value/99*100)), finished=computed(()=>taps.value>=99)
const stage=computed(()=>growth.value>84?"🌻":growth.value>60?"🌿":growth.value>32?"🌱":"🌰")
const rank=computed(()=>growth.value>=86?1:growth.value>=73?2:growth.value>=61?3:4)
const allRacers=computed(()=>players.value.map((p,i)=>({...p,color:["#ff6b55","#f4b83f","#8e78df","#49a96e"][i%4]})).sort((a,b)=>b.score-a.score))
function runTimer(startsAt:number,endsAt:number){if(timer)clearInterval(timer);const tick=()=>{started.value=Date.now()>=startsAt;seconds.value=started.value?Math.max(0,Math.ceil((endsAt-Date.now())/1000)):25};tick();timer=setInterval(tick,100)}
async function syncRoom(){try{const data:any=await $fetch("/api/room");players.value=data.players||[];if(data.state?.phase==="playing"&&(screen.value!=="play"||gameId.value!==data.state.gameId)){gameId.value=data.state.gameId;taps.value=players.value.find(p=>p.id===participantId.value)?.score||0;screen.value="play";runTimer(data.state.startsAt||Date.now(),data.state.endsAt)}if(data.state?.phase==="waiting"&&role.value==="player"&&screen.value==="play")screen.value="waiting"}catch{}}
async function joinRoom(){name.value=name.value.trim().slice(0,12)||"Gardener";ready.value=true;await $fetch("/api/room",{method:"POST",body:{action:"join",id:participantId.value,name:name.value,score:0}});await syncRoom()}
async function startGame(){const data:any=await $fetch("/api/room",{method:"POST",body:{action:"start"}});gameId.value=data.state.gameId;taps.value=0;screen.value="play";runTimer(data.state.startsAt,data.state.endsAt)}
async function leaveGame(){if(role.value==="host"){await $fetch("/api/room",{method:"POST",body:{action:"reset"}});screen.value="lobby"}else screen.value="waiting"}
function water(){if(!started.value||seconds.value<=0||finished.value)return;taps.value=Math.min(99,taps.value+1);if(role.value==="player")$fetch("/api/room",{method:"POST",body:{action:"score",id:participantId.value,name:name.value,score:taps.value,ready:true}}).catch(()=>{})}
onMounted(async()=>{const isPlayer=new URLSearchParams(location.search).has("join");role.value=isPlayer?"player":"host";screen.value=isPlayer?"waiting":"lobby";participantId.value=localStorage.getItem("bloom-rush-player")||crypto.randomUUID();localStorage.setItem("bloom-rush-player",participantId.value);const joinUrl=`${location.origin}${location.pathname}?join=SPROUT`;qr.value=await QRCode.toDataURL(joinUrl,{width:320,margin:2,color:{dark:"#173e2d",light:"#ffffff"},errorCorrectionLevel:"H"});await syncRoom();poller=setInterval(syncRoom,250)})
onBeforeUnmount(()=>{if(timer)clearInterval(timer);if(poller)clearInterval(poller)})
</script>
<template><main class="shell"><nav><a class="brand" href="#"><span>✿</span> BLOOM RUSH</a><div class="live"><i/> ROOM #SPROUT</div></nav>
<section v-if="screen==='lobby'" class="lobby"><div class="intro"><div class="eyebrow">HOST CONTROL</div><h1>Scan. Join.<br><em>Grow!</em></h1><p>Ask every gardener to scan the code. They’ll wait safely in the lobby until you start the race.</p><div class="steps"><span><b>1</b> Scan QR</span><span><b>2</b> Wait in lobby</span><span><b>3</b> Host starts</span></div></div><div class="join-card host-card"><div class="card-top"><span>SCAN TO JOIN</span><strong>#SPROUT</strong></div><img v-if="qr" class="real-qr" :src="qr" alt="QR code to join"><div v-else class="qr-loading">Growing QR…</div><h2>Join the watering race</h2><p>Participants scan this code and wait for you.</p><div class="ready-list"><span v-for="p in players" :key="p.id"><i>{{p.name[0]?.toUpperCase()}}</i>{{p.name}} <b>READY</b></span><span v-if="!players.length">Waiting for gardeners…</span></div><button :disabled="!players.length" @click="startGame">START GAME <span>→</span></button><small><i/> {{players.length}} gardener{{players.length===1?'':'s'}} waiting</small></div></section>
<section v-else-if="screen==='waiting'" class="waiting-page"><div class="waiting-card"><div class="seed-pulse">🌱</div><div class="eyebrow">ROOM #SPROUT</div><h1>You’re in!</h1><p>{{ready?"You’re ready to grow. The game will begin when the host presses Start Game.":"Choose your gardener name, then get ready."}}</p><template v-if="!ready"><label>Your nickname<input v-model="name" maxlength="12" @keyup.enter="joinRoom"></label><button @click="joinRoom">I’M READY <span>→</span></button></template><div v-else class="waiting-status"><i/><b>WAITING FOR HOST</b><span>Keep this page open</span></div><div class="waiting-dots"><i/><i/><i/></div></div></section>
<section v-else class="game"><header class="game-head"><div><button class="back" @click="leaveGame">←</button><span>{{role==='host'?'HOST VIEW':'ROOM #SPROUT'}}</span></div><div class="timer"><small>TIME LEFT</small><b>00:{{String(seconds).padStart(2,'0')}}</b></div><div v-if="role==='host'" class="rank"><small>YOUR RANK</small><b>#{{rank}}</b></div></header><div class="race-grid" :class="{solo:role==='player'}"><div class="garden-panel"><div class="water-drops">💧　💧</div><div class="plant-wrap"><div class="sun">☀</div><div class="plant" :class="{'finished-flower':finished}" :style="{transform:`scale(${.7+growth/260})`}">{{stage}}</div><div class="soil"/></div><div class="growth-copy"><span>YOUR PLANT</span><b>FULL BLOOM GOAL</b></div><div class="meter"><i :style="{width:`${growth}%`}"/></div></div><div v-if="role==='host'" class="leaderboard"><div class="eyebrow">LIVE LEADERBOARD</div><h2>Garden race</h2><div v-for="(r,i) in allRacers" :key="r.name" class="racer" :class="{you:r.name===name}"><strong>{{i+1}}</strong><i :style="{background:r.color}">{{r.name[0]?.toUpperCase()}}</i><span>{{r.name}}<small>{{r.score>=85?'Blooming!':r.score>=60?'Growing strong':'Keep tapping'}}</small></span><b>{{r.score}}%</b></div></div></div><div class="tap-zone"><div><span>{{finished?'🏆':seconds<=0?'⏱':'💧'}}</span><h2>{{finished?'You bloomed!':seconds<=0?'Time’s up!':'Water your plant!'}}</h2><p>{{finished?'Your flower reached a glorious full bloom!':seconds<=0?'The garden needs a little more water.':'Keep tapping to grow a full bloom'}}</p></div><button class="water-btn" :disabled="seconds<=0||finished" @pointerdown="water"><span>💧</span>TAP TO WATER<small>{{finished?'FULL BLOOM!':'KEEP WATERING'}}</small></button></div></section><footer><span>GROW TOGETHER. BLOOM FASTER.</span><span>Made for joyful teams 🌱</span></footer></main></template>
