<script setup lang="ts">
import QRCode from "qrcode"
type Screen = "lobby" | "waiting" | "play"
const racers = [{ name:"Maya",color:"#ff6b55",score:86 },{ name:"Leo",color:"#f4b83f",score:73 },{ name:"Nina",color:"#8e78df",score:61 }]
const role=ref<"host"|"player">("host"), screen=ref<Screen>("lobby"), qr=ref(""), name=ref("You"), ready=ref(false), taps=ref(0), seconds=ref(25)
let room:BroadcastChannel|null=null, timer:ReturnType<typeof setInterval>|null=null
const growth=computed(()=>Math.round(taps.value/99*100)), finished=computed(()=>taps.value>=99)
const stage=computed(()=>growth.value>84?"🌻":growth.value>60?"🌿":growth.value>32?"🌱":"🌰")
const rank=computed(()=>growth.value>=86?1:growth.value>=73?2:growth.value>=61?3:4)
const allRacers=computed(()=>[...racers,{name:name.value,color:"#49a96e",score:growth.value}].sort((a,b)=>b.score-a.score))
function runTimer(){if(timer)clearInterval(timer);timer=setInterval(()=>{if(screen.value==="play"&&!finished.value)seconds.value=Math.max(0,seconds.value-1)},1000)}
function startGame(){taps.value=0;seconds.value=25;screen.value="play";room?.postMessage({type:"start"});runTimer()}
function leaveGame(){if(role.value==="host"){screen.value="lobby";room?.postMessage({type:"reset"})}else screen.value="waiting"}
function water(){if(seconds.value<=0||finished.value)return;taps.value=Math.min(99,taps.value+1)}
onMounted(async()=>{const isPlayer=new URLSearchParams(location.search).has("join");role.value=isPlayer?"player":"host";screen.value=isPlayer?"waiting":"lobby";const joinUrl=`${location.origin}${location.pathname}?join=SPROUT`;qr.value=await QRCode.toDataURL(joinUrl,{width:320,margin:2,color:{dark:"#173e2d",light:"#ffffff"},errorCorrectionLevel:"H"});room=new BroadcastChannel("bloom-rush-sprout");room.onmessage=({data})=>{if(data?.type==="start"){taps.value=0;seconds.value=25;screen.value="play";runTimer()}if(data?.type==="reset"&&isPlayer)screen.value="waiting"}})
onBeforeUnmount(()=>{room?.close();if(timer)clearInterval(timer)})
</script>
<template><main class="shell"><nav><a class="brand" href="#"><span>✿</span> BLOOM RUSH</a><div class="live"><i/> ROOM #SPROUT</div></nav>
<section v-if="screen==='lobby'" class="lobby"><div class="intro"><div class="eyebrow">HOST CONTROL</div><h1>Scan. Join.<br><em>Grow!</em></h1><p>Ask every gardener to scan the code. They’ll wait safely in the lobby until you start the race.</p><div class="steps"><span><b>1</b> Scan QR</span><span><b>2</b> Wait in lobby</span><span><b>3</b> Host starts</span></div></div><div class="join-card host-card"><div class="card-top"><span>SCAN TO JOIN</span><strong>#SPROUT</strong></div><img v-if="qr" class="real-qr" :src="qr" alt="QR code to join"><div v-else class="qr-loading">Growing QR…</div><h2>Join the watering race</h2><p>Participants scan this code and wait for you.</p><div class="ready-list"><span><i>M</i>Maya <b>READY</b></span><span><i>L</i>Leo <b>READY</b></span><span><i>N</i>Nina <b>READY</b></span></div><button @click="startGame">START GAME <span>→</span></button><small><i/> 3 gardeners waiting</small></div></section>
<section v-else-if="screen==='waiting'" class="waiting-page"><div class="waiting-card"><div class="seed-pulse">🌱</div><div class="eyebrow">ROOM #SPROUT</div><h1>You’re in!</h1><p>{{ready?"You’re ready to grow. The game will begin when the host presses Start Game.":"Choose your gardener name, then get ready."}}</p><template v-if="!ready"><label>Your nickname<input v-model="name" maxlength="12"></label><button @click="ready=true">I’M READY <span>→</span></button></template><div v-else class="waiting-status"><i/><b>WAITING FOR HOST</b><span>Keep this page open</span></div><div class="waiting-dots"><i/><i/><i/></div></div></section>
<section v-else class="game"><header class="game-head"><div><button class="back" @click="leaveGame">←</button><span>{{role==='host'?'HOST VIEW':'ROOM #SPROUT'}}</span></div><div class="timer"><small>TIME LEFT</small><b>00:{{String(seconds).padStart(2,'0')}}</b></div><div class="rank"><small>YOUR RANK</small><b>#{{rank}}</b></div></header><div class="race-grid"><div class="garden-panel"><div class="water-drops">💧　💧</div><div class="plant-wrap"><div class="sun">☀</div><div class="plant" :class="{'finished-flower':finished}" :style="{transform:`scale(${.7+growth/260})`}">{{stage}}</div><div class="soil"/></div><div class="growth-copy"><span>YOUR PLANT</span><b>FULL BLOOM GOAL</b></div><div class="meter"><i :style="{width:`${growth}%`}"/></div></div><div class="leaderboard"><div class="eyebrow">LIVE LEADERBOARD</div><h2>Garden race</h2><div v-for="(r,i) in allRacers" :key="r.name" class="racer" :class="{you:r.name===name}"><strong>{{i+1}}</strong><i :style="{background:r.color}">{{r.name[0]?.toUpperCase()}}</i><span>{{r.name}}<small>{{r.score>=85?'Blooming!':r.score>=60?'Growing strong':'Keep tapping'}}</small></span><b>{{r.score}}%</b></div></div></div><div class="tap-zone"><div><span>{{finished?'🏆':seconds<=0?'⏱':'💧'}}</span><h2>{{finished?'You bloomed!':seconds<=0?'Time’s up!':'Water your plant!'}}</h2><p>{{finished?'Your flower reached a glorious full bloom!':seconds<=0?'The garden needs a little more water.':'Keep tapping to grow a full bloom'}}</p></div><button class="water-btn" :disabled="seconds<=0||finished" @pointerdown="water"><span>💧</span>TAP TO WATER<small>{{finished?'FULL BLOOM!':'KEEP WATERING'}}</small></button></div></section><footer><span>GROW TOGETHER. BLOOM FASTER.</span><span>Made for joyful teams 🌱</span></footer></main></template>
